# Build command
[build]

    # Source directory
    base = "."

    # Build file directory
    publish = "dist"

    # Build file command.
    command = "npm install && vite build && cp -r weeks dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200